### ISSUE TITLE
import error on OS X

### ISSUE THREAD

**Issue by ckalas** [strawlab/python-pcl#63]
Cython version 0.21.2
pcl installed through home-brew

I've tried remaking and making clean, but I still wind up with this error:

Python 2.7.8 (v2.7.8:ee879c0ffa11, Jun 29 2014, 21:07:35) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pcl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pcl/__init__.py", line 2, in <module>
    from ._pcl import *
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pcl/_pcl.so, 2): Symbol not found: __ZN3pcl6search6SearchINS_8PointXYZEE13setInputCloudERKN5boost10shared_ptrIKNS_10PointCloudIS2_EEEERKNS5_IKSt6vectorIiSaIiEEEE
  Referenced from: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pcl/_pcl.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pcl/_pcl.so

**Comment by ckalas** [comment]
Seemingly upgrading pip to the latest version and then reinstalling with pip -install -upgrade resolved this.

**Comment by toinsson** [comment]
Got the same problem.. what did you reinstall with pip? another version of cython?

**Comment by mikeroberts3000** [comment]
I ended up finding an astonishing workaround for this issue.

When I run ``python setup.py install``, the setup script prints out a few gcc and g++ commands (see above). If you can believe it, the workaround for this problem was to take each gcc and g++ command, copy it to the command line, and run it manually. And then to run ``python setup.py install`` again. Running the setup script again will not call gcc or g++, but will copy the relevant files to the Python site-packages folder.

So, the build environment is somehow different when invoking gcc and g++ from setup.py, as opposed to invoking gcc and g++ manually from the command line.

There are several open issues where other people have similar errors (https://github.com/strawlab/python-pcl/issues/63, https://github.com/strawlab/python-pcl/issues/101, https://github.com/strawlab/python-pcl/issues/119), so I don't think this issue is due to a local build configuration problem on my machine.
